# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: user123
                        roles: 'ROLE_USER'
                    admin:
                        password: admin123
                        roles: 'ROLE_ADMIN'

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # ...
            pattern: ^/
            anonymous: ~
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   /logout
                target: /


            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

