# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    product_handler:
        class: AppBundle\Products\Handler\NewProductHandler
        arguments: ['@doctrine.orm.entity_manager', '@validator', '@app_mailer']

    app_mailer:
        class: AppBundle\Products\NewProductNotificationSender
        arguments: ['@swiftmailer.mailer']