# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    product_handler:
        class: AppBundle\Products\Handler\NewProductHandler
        autowire: true

    products_doctrine:
        class: AppBundle\Products\Query\DoctrineProducts
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']